apiVersion: apps/v1
kind: Deployment

metadata:
  name: service2

spec:
  replicas: 2

  selector:
    matchLabels:
      app: service2

  template:
    metadata:
      labels:
        app: service2

    spec:
      containers:
      - name: service2
        image: host.minikube.internal:5000/service2:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service

metadata:
  name: service2

spec:
  selector:
    app: service2

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80